#
# Build configuration for Circle CI
#

general:
    artifacts:
        - /home/ubuntu/UnitTestWithCircleCI/app/build/outputs/apk/
general:
     branches:
        only:
          - master # list of branches to ignore


machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-25.0.2,android-25,extra-google-m2repository,extra-android-m2repository,extra-google-google_play_services,extra-android-support
        - chmod +x gradlew
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies --console=plain

test:
    override:
        - (./gradlew assemble):
            timeout: 360
 # start the emulator
        - emulator -avd circleci-android22 -no-audio -no-window:
            background: true
            parallel: true
        # wait for it to have booted
        - circle-android wait-for-boot
        # unlock the emulator screen
        - sleep 30
        - adb shell input keyevent 82
        # copy the build outputs to artifacts
        - cp -r app/build/outputs $CIRCLE_ARTIFACTS